name: descarga_indec

on: 
  push:
  schedule:
   - cron: '0 20 * * * '

jobs:
  render:
    name: descarga_indec
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Run R script
        run: Rscript gha_downloader.R
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Actualizo users" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
